# Generated by Django 5.2.17 on 2026-10-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffreApp', '0001_initial'),
        ('VehiculeApp', '0002_alter_vehicule_capacite_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='vehicule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offres_vehicule', to='VehiculeApp.vehicule'),
            preserve_default=False,
        ),
    ]
