# Generated by Django 5.2.17 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
