# Generated by Django 5.2.17 on 2026-10-06 15:17

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0002_alter_utilisateur_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "L'adresse ne peut pas pas avoir moins de 20 caractères"), django.core.validators.MaxLengthValidator(400, "L'adresse ne peut pas pas avoir plus de 400 caractères")]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
    ]
