# Generated by Django 5.2.17 on 2026-10-06 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, 'La capacité doit être supérieure à 100')]),
        ),
    ]
